In [3]:
#%% 1. Numbers
 
int_number = 1
float_number = 1.0
complex_number = 1 + 2j
round_float = round(1234.5678, 2)
str2int = int('213')
 
print(round_float)


1234.57


In [16]:
number_list = [0, 1, 1, 2, 3, 5, 8]
slicing_4_a_specific_pos = number_list[3]
slicing_4_the_last_pos = number_list[-1]
slicing_4_consecutive_pos = number_list[0:3]
slicing_4_the_last_three = number_list[-3:]
 
list_list = [[1, 2, 3], [4, 5, 6]]  # list of list
A_list = list_list[0]
A_ist_list = list_list[0:2]
A_number = list_list[1][2]


In [17]:
# Array and slicing
import numpy as np
  
a = np.array([1, 2, 3]) # a vector has no direction
A = np.array([[1, 2, 3]]) # a 1 x 3 array that can be transposed
a_T = a[:, np.newaxis] # a' although a has no direction
A_T = A.T # A'
B = A.reshape(-1, 1) # A'
C = np.array([1, 2, 3], ndmin = 2) # convert a to A
print(np.size(a))  # == print(a.size) number of elements in a
print(np.shape(A_T))  # == print(A_T.shape) , array dimension
 
D = np.array([[1, 2, 3],[4, 5, 6]])
print(D[1]) # D[1] = D[1,:] # second row and all columns
print(D[:, 1])
print(D[:, 0:-1])
print(D[:, 1:])
print(D[:, -2:])

3
(3, 1)
[4 5 6]
[2 5]
[[1 2]
 [4 5]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]


In [6]:
# vector concatenation
 
va = np.array([1, 2, 3])
vb = np.array([4, 5, 6])
vc = np.concatenate((va, vb), axis = 0) # flatten a, b; try axis=1
vd = np.append(va, vb)
ve = np.hstack((va, vb)) 
vF = np.vstack((va, vb))
vg = np.r_[va, vb]
vG = np.c_[va, vb]
vH = (va, vb) # a tuple

In [7]:
#matrix concatenation
 
ma = np.array([[1, 2, 3]]) # 1 x 3
mb = np.array([[4, 5, 6]]) # 1 x 3
mc = np.hstack((ma, mb))   # 1 x 6
  
# Vertically, concatenate row-wisely 
mC = np.concatenate((ma, mb), axis = 0) # 2 x 3
mD = np.r_[ma, mb] # 2 x 3
mE = np.vstack((ma,mb)) #2 x 3
  
# Horizontally, concatenate column-wisely
mF = np.concatenate((ma.T, mb.T), axis =1) # 3 x 2
mG = np.hstack((ma.T, mb.T)) # 3 x 2
mH = np.c_[ma.T, mb.T] # 3 x 2

In [8]:
S = np.array([[1, 3, 2], [6, 5, 4]])
print(S)
print(S.max())
print(S.max(0)) # column max
print(np.max(S, axis = 1)) # row max
 
a = S.flatten() # turn into vector
b = S.flatten('F') # turn into vector column-wise
S[S < 3] = 0 # check what S looks like
 
c = [1, 2, 3, 4]
C = np.tile(c,(5,1)) # 5 x 4 matrix
d = np.reshape(C, (-1, 1)) # convert to Column vector

[[1 3 2]
 [6 5 4]]
6
[6 5 4]
[3 6]


In [9]:
a_tuple = (0, 0) # ordered sequence
also_a_tuple = 0, 0
a_3d_tuple = (0, 1, 2) # (2,1,0) is different, however the list  [0,1,2] := [1,2,0]

In [10]:
import numpy as np
 
Z = np.zeros((3,4)) # 3 x 4 zero matrix
One =  np.ones((3,4)) # 3 x 4 one matrix
I = np.eye(3) # 3 x 3 identity matrix
D = np.diag([1, 2, 3, 4]) # a diagonal matrix
e = np.diag(I) # the diagonal of I

In [11]:
import numpy as np
  
x0 = [1, 2, 3, 4, 5, 6, 7, 8, 9] # a list
x1 = range(1, 10, 1) # a range
x2 = np.arange(1, 10, 1)  # an array of integer numbers
x3 = np.linspace(1, 9, 9)  # an array of float number
x4 = np.arange(10)  # start from 0 to 9
x5 = np.linspace(0, 100, 1000)
 
y1 = x2 + x3 + 1 # not x0 + x1 + 1
y2 = x2 ** 2 + x2 - 2
y3 = x2 / x3

In [12]:
#%% string & indexing
  
s1 = 'a single quote string'
s2 = "a double quote string"
s3 = '''a triple quote string'''
  
print(s3[0])
print(s2[:4])
print(s3)
  
s4 = """
Triple double quotes
is usually used
in multiple lines, such as documents
"""
print(s4)
 
# concatenate strings
s5 = 'This is ' + s1
  
# string list
str_list = ['r', 'g', 'b', 'k', 'y']
print(str_list[1])
  
# Dictionaries
meals = {'breakfast': 'sardines', 'lunch': 'salad', 'dinner': 'cake', 'cost':40}
print(meals['breakfast'])
print(meals['cost'])
print('The meal costs {} dollars'.format(meals['cost']))  

a
a do
a triple quote string

Triple double quotes
is usually used
in multiple lines, such as documents

g
sardines
40
The meal costs 40 dollars


In [13]:
col_names = ['col1', 'col2', 'col3'] # string list
col_names_join = ','.join(col_names) # convert to a string
col_names_split = col_names_join.split(',') # convert a string to a list
 
a_sentence = "台北大學統計系"
where_am_I = a_sentence.find('統計')
where_is_it = a_sentence.find('會計') # -1 means NOT FOUND

In [14]:
from numpy import linalg
import numpy as np 
import scipy.linalg as LA # scipy's linear algebra is better
 
X = np.array([[1,2,3],[4,5,6]]) # a 2x3 matrix
# check the information of X
Xdim = X.ndim
Xshape = X.shape
Xsize = X.size
 
a = X[0, 1]
P = X * X # element by element multiplication
Q = X / X # element by element division
R = X @ X.T # XX'
 
total_sum = X.sum() # X.mean()...
row_sum = X.sum(axis = 1) # sum over each row
col_sum = X.sum(axis = 0) # sum over each column
# col_sum = np.sum(X, axis = 0) 
 
A = np.array([[1, 1, 1],[2, 4, 6],[5, 7, 6]])
b = np.array([1, 2, 3])
x =  LA.inv(A) @ b  # Ax = b
xsol = LA.solve(A, b) # Ax = b
I = A @ LA.inv(A) # double check what LA.inv(A) is
 
A_square = linalg.matrix_power(A, 2) # nth power of a matrix
A_square_root = LA.fractional_matrix_power(A, 0.5)
 
B = np.vstack((A, b)) # 4 x 3
C = np.hstack((A, b.reshape(3, 1))) # 3 x 4
 
B_row = np.insert(A, 3, b, 0) # 3 is the position index; 0 is for row
B_col = np.insert(A, 3, b, 1) # 3 is the position index; 1 is for column

In [15]:
import numpy as np 
  
x = np.array([1, 2, 5, 3, 2])
x[x > 3] = 9 # replaced by 9; conditioned on x>3
y = np.where(x > 3, 9, x)
z = np.where(x >=3, 1, 0)
#-------------------------------
p = [] # p is a empty list
print(not p)  # check if p is empty or not
# print(p is None) 
# Check whether variable p is defined or not
print('p' in locals())
#-------------------------------
a = 3
if a > 1 and a < 5 :
    print('TRUE')
else :
    print('FALSE')
  
if a > 5 or a < 1 :
    print('OUTSIDE')
else :
    print('INSIDE')
#-------------------------------
# compact expression for if...else...
flag = 1
status = "play" if flag ==1 else "stop"
print(status)

True
True
TRUE
INSIDE
play
